import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "../styles/main/globals.scss";
import { ChakraProvider } from "@chakra-ui/react";
import ClientProvider from "./ClientProvider";

const OpenSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Charty",
  description: "Generated by create next app",
  icons: {
    icon: [
      './favicon/favicon.ico?v=4',
    ],
    apple: [
      './favicon/apple-touch-icon?v=4',
    ],
    shortcut: [
      './favicon/apple-touch-icon.png',
    ],
  },
  // manifest: '/site.webmanifest',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ChakraProvider theme={theme}>
      <html lang="en">
        <body className={OpenSans.className} suppressHydrationWarning={true}>
          {/* <div className="wrapper"> */}
          <ClientProvider>
            {children}
          </ClientProvider>
          {/* </div> */}
        </body>
      </html>
    // </ChakraProvider>
  );
}